# Generated by Django 5.2.7 on 2025-10-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_class_class_cancellations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_cancellations',
        ),
        migrations.RemoveField(
            model_name='class',
            name='homeworks',
        ),
        migrations.RemoveField(
            model_name='class',
            name='memos',
        ),
        migrations.AddField(
            model_name='class_cancellation',
            name='class_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
        migrations.AddField(
            model_name='homework',
            name='classModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
        migrations.AddField(
            model_name='memo',
            name='class_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
