# Generated by Django 5.2.7 on 2025-10-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_class_class_cancellations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day_of_the_week',
            field=models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日')], verbose_name='曜日'),
        ),
    ]
