# Generated by Django 5.2.7 on 2025-11-21 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_class_examination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='day_of_the_week',
        ),
        migrations.RemoveField(
            model_name='class',
            name='period',
        ),
        migrations.CreateModel(
            name='Class_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日')], verbose_name='曜日')),
                ('period', models.IntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目'), (5, '5限目'), (6, '6限目'), (7, '7限目'), (8, '8限目')], verbose_name='時限')),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
    ]
