# Generated by Django 5.2.7 on 2025-11-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_class_day_of_the_week_remove_class_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='class_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
