# Generated by Django 5.2.7 on 2025-11-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_class_schedule_class_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='class_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
            preserve_default=False,
        ),
    ]
