# Generated by Django 5.2.7 on 2026-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_homework_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目'), (5, '5限目'), (6, '6限目'), (7, '7限目'), (8, '8限目')], verbose_name='時限')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
            ],
        ),
    ]
