# Generated by Django 5.2.7 on 2026-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_timeframe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='色'),
        ),
    ]
